#!/bin/sh
#set -x

case "${1}" in
   start)
      logger -p info -s "Starting mosquitto"

      if ! mosquitto -c /etc/mosquitto/mosquitto.conf -d ; then
         if ! ifconfig eth0 | grep -q "inet addr" && ! ifconfig wlan0 | grep -q "inet addr"; then
           logger -p err "Failed to start mosquitto"
         fi
      fi
      ;;

   stop)
      logger -p info -s "Stopping mosquitto"
      terminate_verify mosquitto
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: $0 [start|stop|restart]"
      ;;
esac